import turtle
t=turtle.Turtle()
s=turtle.Screen()
t.hideturtle()
s.screensize(400,400)
s.bgcolor("black")
s.title("Oxymeter")
t.color("pink")
s.bgpic("lungs2.gif")
t.penup()
t.setpos(0,300)
t.color("#cf7d46")
t.write("IF YOU CAN DO THIS,THEN YOU ARE FREE FROM CORONA!!", align="center",font=("Arial",20,"normal"))
t.setpos(0,200)
t.color("#94712f")
t.write("Inhale when red dot moves to A ,hold the breath when red dot moves A to B...", align="center",font=("Arial",15,"normal"))
t.home()
t.color("white")
t.bk(120)
t.pendown()
t.setheading(90)
t.fd(100)
t.setheading(0)
t.fd(225)
t.setheading(270)
t.fd(200)
t.setheading(180)
t.fd(225)
t.setheading(90)
t.fd(200)
t.penup()
t.fd(3)
t.color("#ab7f43")
t.write("A", align="left",font=("Arial",8,"normal"))
t.setheading(0)
t.fd(225)
t.write("B", align="left",font=("Arial",8,"normal"))
t.home()
t.bk(150)
t.setheading(0)
t.color("#ab7f43")
t.write("Inhale", align="center",font=("Arial",15,"normal"))
t.home()
t.fd(150)
t.write("Exhale", align="center",font=("Arial",15,"normal"))
t.home()
t.setheading(90)
t.fd(120)
t.write("Hold Breath", align="center",font=("Arial",15,"normal"))
t.bk(20)
t.setheading(180)
t.fd(120)
t.setheading(270)
t.fd(200)
t.setheading(90)
t.showturtle()
t.color("white","red")
t.shape("circle")
t.turtlesize(0.5)
s.delay(200)
t.fd(200)
s.delay(0.5)
t.setheading(0)
s.delay(1475)
t.fd(225)
s.delay(0)
t.setheading(270)
t.fd(200)
t.setheading(180)
t.fd(225)



turtle.done()
